### ISSUE TITLE
says I am on legacy bio when in fact im on uefi

### ISSUE THREAD

**Issue by troysjanda** [orangegrouptech/Windows-11-Compatibility-Checker#1]
![notright](https://user-images.githubusercontent.com/24624945/123733936-436b7b00-d851-11eb-8ad0-3c416ee8e5bc.PNG)

**Comment by orangegrouptech** [comment]
Thank you for reporting the issue. I have rolled out Patch 1.3.1, which should fix the issue. Could you help me test this? Thanks.

**Comment by mads1153** [comment]
Also the text for this BIOS mode just is black on Dark Mode.

**Comment by orangegrouptech** [comment]
this issue was fixed in Patch 1.3.2 that i rolled out a few hours ago

**Comment by mads1153** [comment]
Yes, it works now 👍 

So I think this issue can now be closed.

**Comment by troysjanda** [comment]
Closed as fixed
