### ISSUE TITLE
How do i open it?

### ISSUE THREAD

**Issue by Porua** [orangegrouptech/Windows-11-Compatibility-Checker#11]
Hello, How can i open the Compatibility i tried the zip file won't work.

**Comment by orangegrouptech** [comment]
Which zip file?
Download the exe file in the Releases tab, the zip file you downloaded is probably for the source code.

**Comment by Porua** [comment]
Where? 
![Github](https://user-images.githubusercontent.com/87680534/126355072-c48e969e-8581-4fb4-8958-8cfffed4828f.png)

**Comment by krystian3w** [comment]
right column 🤯  - > Releases

or use this: https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/releases/latest

**Comment by Porua** [comment]
Thank you!
