### ISSUE TITLE
V2.3 does hang during DirectX WWDDM2 check on my W10 21H1 PC

### ISSUE THREAD

**Issue by 100PIER** [orangegrouptech/Windows-11-Compatibility-Checker#12]
Previous version was OK, new version does hang immediatly

**Comment by ThePhOeNiX810815** [comment]
can you try to run app as Administrator ?

**Comment by ThePhOeNiX810815** [comment]
@orangegrouptech  I've changed DXVersion data type for comparison, can you please check it ? ... I think comparison may crash if version is decimal format (for example 11.1, 11.2) during parse to long.

[GPU Check.txt](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/6866996/GPU.Check.txt)

**Comment by orangegrouptech** [comment]
ah yeah. it was probably trying to convert to int and it can't since there's a decimal. i'm going to roll out a patch soon

**Comment by orangegrouptech** [comment]
Try this out
This is a prerelease build, so if you click check for updates it'll give you a warning. Just ignore it since you guys are authorised to test this build

[Windows 11 Compatibility Checker WPF.zip](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/6867062/Windows.11.Compatibility.Checker.WPF.zip)

**Comment by 100PIER** [comment]
Hello,

I tried this beta, and got the same crash :

 

W11_Compatibility_Checker_beta_crash_23juillet21.PNG

Regards

Alain

De : Orange Group Tech ***@***.*** 
Envoyé : vendredi 23 juillet 2021 09:05
À : orangegrouptech/Windows-11-Compatibility-Checker
Cc : 100PIER; Author
Objet : Re: [orangegrouptech/Windows-11-Compatibility-Checker] V2.3 does hang during DirectX WWDDM2 check on my W10 21H1 PC (#12)

 

Try this out
This is a prerelease build, so if you click check for updates it'll give you a warning. Just ignore it since you guys are authorised to test this build

Windows <https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/6867062/Windows.11.Compatibility.Checker.WPF.zip>  11 Compatibility Checker WPF.zip

**Comment by orangegrouptech** [comment]
Could you reply using the GitHub website? I can't see the picture you sent.

**Comment by 100PIER** [comment]
OK, I tried under administrator. here the W10 reliability panel screenshot, and GPUZ screenshots.
![W11_Compatibility_Checker_beta_crash_23juillet21](https://user-images.githubusercontent.com/45947394/126777084-f43d1309-1f5b-48f4-a4e7-de2bc9aa5a84.PNG)
![W11_Compatibility_Checker_beta_crash_GPUZ_infos_23juillet21](https://user-images.githubusercontent.com/45947394/126777614-680df80e-095c-4296-bd5e-ef832ce9898d.PNG)
![W11_Compatibility_Checker_beta_crash_GPUZ_WDDM_details_23juillet21](https://user-images.githubusercontent.com/45947394/126777652-6510df11-10a9-4e67-9d10-cfe23bb12313.PNG)

**Comment by 100PIER** [comment]
hello,

is there a new version without this problem which do occur on 3 different PCs on my side ?

**Comment by 100PIER** [comment]
Any progress on a new version without the crash issue ?

**Comment by orangegrouptech** [comment]
Try Patch 2.3.1

**Comment by 100PIER** [comment]
I have tryed Patch 2.3.1 , the crash problem is not fixed;
Tested as admin on 3 different PCs: same issue.
![W11_Compatibility_Checker_v231_crash_26juillet21](https://user-images.githubusercontent.com/45947394/126967560-162b760b-d04a-4702-8cc8-f65f3198dbd3.PNG)

**Comment by orangegrouptech** [comment]
I'll prepare a debug version of this app later for further diagnosis

**Comment by orangegrouptech** [comment]
> Previous version was OK, new version does hang immediatly

Also which version do you mean

**Comment by ThePhOeNiX810815** [comment]
try to use debug build from Issue #13 uploaded by me, we've got detailed information about crash

**Comment by 100PIER** [comment]
Version such as v2.0.3 does work fine on any 3 different  PCs i have!
Version v2.3.1 does crash on any 3 different PCs I have !

No progress to get a non bugged version to replace v2.3.1 ?

**Comment by ThePhOeNiX810815** [comment]
@100PIER try to use debug build from Issue #13 uploaded by me, we've got detailed information about crash

**Comment by 100PIER** [comment]
The debug build on #13 has no .exe file ! Please can you explain how to use it ? It does contain a src sub-folder. please can you explain ?

**Comment by 100PIER** [comment]
CRASH reported by W10
![W11_Compatibility_Checker_CRASH_31juillet21](https://user-images.githubusercontent.com/45947394/127744154-c1d6f3f3-23ac-4666-b38d-5bd5efe0f130.PNG)

**Comment by ThePhOeNiX810815** [comment]
@100PIER I'm sorry, my fault ... I've uploaded only source solution ... debug EXE build here ... please use it, when report comes I'll check the problem and give you back ;-)

[W11-COMPAT-CHECK-DEBUG.zip](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/6911368/W11-COMPAT-CHECK-DEBUG.zip)

**Comment by 100PIER** [comment]
Thanks for the proper versionv2.3.1 with embedded Debugger.
Here are the 2 screenshots of the test.
![W11_Compatibility_Checker_DEBUG_version_CRASH_31juillet21](https://user-images.githubusercontent.com/45947394/127745863-31ba9e0f-ceab-48ae-8576-e22fc4c8b4a0.PNG)
![W11_Compatibility_Checker_DEBUG_version_CRASH_up_to_completion_31juillet21](https://user-images.githubusercontent.com/45947394/127745866-48f261bd-3b59-43b1-93e7-78c7ffb3b843.PNG)
What is your analysis of this bug situation ?

**Comment by ThePhOeNiX810815** [comment]
@100PIER thanks a lot for report ... I localized source of the issue, but can I please you run once again this new debug build ? ... I added some more details output ... after this I will be able to completely reproduce your execution and finally fix it ... thanks

[W11-COMPAT-CHECK-DEBUG-2.zip](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/6911552/W11-COMPAT-CHECK-DEBUG-2.zip)

**Comment by 100PIER** [comment]
I tested with Debug2. I got the same screenshots as above. The only difference is the Title where (Debug version) is displayed in the main screen.
But where are located the 'details output' do you want ? 
Is there somewhere a log trace which can help you ?

**Comment by 100PIER** [comment]
does the problem during the GPU checking phase ? (the button does remain blue)

**Comment by 100PIER** [comment]
Screenshot on a W10 machine not W11 compatible.
![W11_Compatibility_Checker_DEBUG_2_version_CRASH_31juillet21](https://user-images.githubusercontent.com/45947394/127748370-ac40e33f-367d-4b29-8a44-8db90e227a23.PNG)
![W11_Compatibility_Checker_DEBUG_2_version_CRASH_up_to_completion_31juillet21](https://user-images.githubusercontent.com/45947394/127748374-9d4d6335-e07f-431c-9bed-142e99b70d36.PNG)

**Comment by 100PIER** [comment]
Screenshot on a W10 Z390M machine compatible W11.
What is the e-mail problem ?
![W11_Compatibility_Checker_DEBUG_2_version_Z390M_W11_compatible_31juillet21](https://user-images.githubusercontent.com/45947394/127748626-194da69f-ee9f-4cc3-bb42-d3e2610dae06.PNG)
![W11_Compatibility_Checker_DEBUG_2_version_Z390M_up_to_completion_W11_compatible_31juillet21](https://user-images.githubusercontent.com/45947394/127748634-c4f2b9c2-3ee3-4203-b259-242d93a36bb4.PNG)

**Comment by ThePhOeNiX810815** [comment]
@100PIER thanks a lot ... now I have enough info, I'm going to fix it

The report came to me by e-mail in following form:

![image](https://user-images.githubusercontent.com/23176319/127749067-ec9a9ea8-3824-4a5b-b724-a0c119570226.png)

**Comment by ThePhOeNiX810815** [comment]
@100PIER well done, fixed ... thanks for tests ;-)

[Windows-11-Compatibility-Checker-2.3.2.zip](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/6911692/Windows-11-Compatibility-Checker-2.3.2.zip)

**Comment by ThePhOeNiX810815** [comment]
@100PIER the e-mail issue on your W10 Z390M looks like some network problem, maybe some firewall, NAT or anti-virus program is blocking port 25 [SMTP]

**Comment by 100PIER** [comment]
The provided  2.3.2.zip file does not contain any  .exe application. 
Is it possible to get this new v2.3.2 version to do some  tests with  it ?
About anti-virus I do use IOBit Malware Fighter PRO on the 3 different PCs

**Comment by ThePhOeNiX810815** [comment]
@100PIER sorry, try this:
[Windows-11-Compatibility-Checker-2.3.3.zip](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/6912201/Windows-11-Compatibility-Checker-2.3.3.zip)

GPU check might work there, but there are already some issues, wait a while for new release version.

**Comment by 100PIER** [comment]
Thanks, however i see no .exe into 2.3.3.zip file.

**Comment by ThePhOeNiX810815** [comment]
@100PIER hi, just navigate to "Windows-11-Compatibility-Checker-2.3.3\src\bin\Debug\net45" to EXE ...

**Comment by 100PIER** [comment]
Thanks, I tried it:
The 'Debug' info does no longer exist ?
Always same problem.
![W11_Compatibility_Checker_v2330_CRASH_01aout21](https://user-images.githubusercontent.com/45947394/127762061-1edbecc7-d636-48e1-8d99-5f74728a5ba2.PNG)
Let me know when i can help you for testing.
Thanks for your support, be quiet to fix the problem, do take your time, there is no urgency !

**Comment by ThePhOeNiX810815** [comment]
@100PIER hi, I've fixed some GFX and TPM checks issues, please, try this pre-release version ...thanks

Executable is in "src\bin\Debug\net45" folder.

[Windows-11-Compatibility-Checker-2.3.4.zip](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/6912624/Windows-11-Compatibility-Checker-2.3.4.zip)

**Comment by 100PIER** [comment]
Tested v2.3.4 on 2 different machines (report done at #13), all is OK now. Thanks for the very good job !!

**Comment by ThePhOeNiX810815** [comment]
@100PIER thanks a lot for your patience and testing ;-)

**Comment by orangegrouptech** [comment]
I just pushed out Patch 2.3.2 that includes these fixes. You guys can try it out and see if it works.

**Comment by 100PIER** [comment]
I see on majorgeeks you pushed out a v2.3.2, and I have done tests with it , all is OK for me on my side.
However the 'check update' function is totally confusing because proposal offered to the user does seem 'outdated'..

**Comment by orangegrouptech** [comment]
Oh no, I forgot to update version.txt in my haste to push out the update

**Comment by orangegrouptech** [comment]
Alright, fixed that

**Comment by orangegrouptech** [comment]
And wait what, it's on MajorGeeks?

**Comment by 100PIER** [comment]
Not yet perfect.
Majorgeeks on 1st aug does offer v2.3.2, and "check update" does propose a very confusing menu:
![W11_Compatibility_Checker_v2320_02aout21](https://user-images.githubusercontent.com/45947394/127822906-809b3e67-b271-457a-933e-60e1aa4c45c6.PNG)

**Comment by orangegrouptech** [comment]
Oh no, that requires a change to the app code itself. I'll patch it later and find an alternative to this potato code

**Comment by ThePhOeNiX810815** [comment]
@orangegrouptech I think it's fine, but 'Check for Updates' version comparison shall be comparing only major.minor. In this case, every X.X.X build will be treated as 'patch' or 'pre-release' version

**Comment by orangegrouptech** [comment]
yeah but we do want people to update to patches sometimes

**Comment by orangegrouptech** [comment]
Actually I'll patch it in the next update. However I'm having some trouble implementing it so it may take a few days

**Comment by orangegrouptech** [comment]
I just pushed out version 2.4 that should fix this issue. You can try it out.

**Comment by 100PIER** [comment]
Tested v2.4.0.0 on my PCs.  Check update problem well fixed.
![W11_Compatibility_Checker_v2400_05aout21](https://user-images.githubusercontent.com/45947394/128299650-45cd97ee-af15-49d9-a6ef-00e552bbe047.PNG)

**Comment by 100PIER** [comment]
I don't understand where you can obtain the v2.4 stable version with Debugger Mode activate ? The .zip folder does not contain bin subfolder.

**Comment by orangegrouptech** [comment]
Debug Mode is implemented directly into version 2.4.

**Comment by 100PIER** [comment]
Is it activate permanently ? or can we active/deactive the Debug Mode as usually any Application Tool does offer ?

**Comment by orangegrouptech** [comment]
On default, it will prompt you every time an error occurs asking if you want to send the diagnostic data. It'll look like this:

![image](https://user-images.githubusercontent.com/63195743/128302367-69034b09-eac5-42dd-b330-a951627d7d1c.png)
More information about the privacy is here: https://gist.github.com/orangegrouptech/e9e15471df7462319fd1887db42d1d97

**Comment by 100PIER** [comment]
Thanks, I understand the activation is automatic. However, any  potential compatibility with some firewall (Freebox) or antivirus application when Send Report is selected ? Do we have to 'white list' permanently this application ?

**Comment by orangegrouptech** [comment]
Probably not since this works by sending the data to my email

**Comment by orangegrouptech** [comment]
Though if sending fails it'll tell you

**Comment by 100PIER** [comment]
OK, I understand. I do remember when I have used the Debug version during the test phase, few days ago, the sending did fail when using my Freebox server, but when using my 'share connection' on the smartphone the sendind report was OK. At the moment I don't how to 'educate' the Freebox server to modify its default parameters to authorize your 'send report'. May be this limitation is just for Free Telecom operator in France. Thanks for your time for your support. Yes, we can close the thread #12

**Comment by ThePhOeNiX810815** [comment]
@100PIER i think only requirement to send error e-mail report is open port 25, for SMTP
