### ISSUE TITLE
Windows compatibility checker crash

### ISSUE THREAD

**Issue by Porua** [orangegrouptech/Windows-11-Compatibility-Checker#13]
When i click on the program it crash. Help. Version 2.3

**Comment by Porua** [comment]
Won't work

**Comment by orangegrouptech** [comment]
At which part of the app would it crash? If it's during the GPU check, it will stop responding after a while, don't click on the window or it may crash, just wait it out.

**Comment by orangegrouptech** [comment]
Ignore what I said above, try this build, does it work?
This is a prerelease build, so if you click check for updates it'll give you a warning. Just ignore it since you are authorised to test this build

[Windows 11 Compatibility Checker WPF.zip](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/6867063/Windows.11.Compatibility.Checker.WPF.zip)

**Comment by Porua** [comment]
It's cheking CPU it crash.

**Comment by orangegrouptech** [comment]
What CPU do you have?

**Comment by Porua** [comment]
I have AMD A9

**Comment by Porua** [comment]
I have an AMD Radeon R5 Graphics or AMD A9

**Comment by orangegrouptech** [comment]
Weird, maybe try version 2.3.1?

**Comment by Porua** [comment]
Same problem.

**Comment by Porua** [comment]
If you wanna know i have Windows 10 21h2 build: 19044.1147

**Comment by Porua** [comment]
Maybe is the code?

**Comment by orangegrouptech** [comment]
I don't think so. Works for me and for a lot of other people.
I'll send the debug version later for further diagnosis

**Comment by orangegrouptech** [comment]
Try this version of the app and tell me what error it shows

[Windows 11 Compatibility Checker WPF.zip](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/6877392/Windows.11.Compatibility.Checker.WPF.zip)

**Comment by ThePhOeNiX810815** [comment]
Hi folks

I've already created debug version with mail notification. Check it out, maybe it helps in future or another project.

[Windows-11-Compatibility-Checker-main.zip](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/6877538/Windows-11-Compatibility-Checker-main.zip)

**Comment by 100PIER** [comment]
v2.3.1 does hang on my 3 PCs W10 64bits 21H1 build 19043.1151 whatever are the hardware configurations.
Old version v2.0.3 did not hang on the same PCs

**Comment by ThePhOeNiX810815** [comment]
@Porua hi, I've fixed some GFX and TPM checks issues, please, try this pre-release version ...thanks

Executable is in "src\bin\Debug\net45" folder.

[Windows-11-Compatibility-Checker-2.3.4.zip](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/6912624/Windows-11-Compatibility-Checker-2.3.4.zip)

**Comment by 100PIER** [comment]
v2.3.4 test does work correctly on my X99 machine (not W11 compatible)
I will do test soon on a Z390M machine (W11 compatible) and will join soon a screenshot.

On X99 machine (not W11 compatible):
![W11_Compatibility_Checker_v2340_X99_01aout21](https://user-images.githubusercontent.com/45947394/127771808-7d5beaaa-3ae6-4949-b7e6-ea7014499d21.PNG)

**Comment by 100PIER** [comment]
v2.3.4 does work on a Z390M machine (W11 compatible).
Thanks for the very quick fix:
![W11_Compatibility_Checker_v2340_Z390M_01aout21](https://user-images.githubusercontent.com/45947394/127772387-f525adb5-6acc-47dd-873c-a193093bd5e4.PNG)

**Comment by ThePhOeNiX810815** [comment]
@100PIER thanks very much for tests ... great ;-) ... now we just wait for @orangegrouptech to push official release

**Comment by orangegrouptech** [comment]
I just pushed out Patch 2.3.2 that includes these fixes. You guys can try it out and see if it works.

**Comment by orangegrouptech** [comment]
@100PIER does the update work for you?

**Comment by 100PIER** [comment]
YES, i have already replied in #12.
v2.3.2 offered on majorgeeks site does work fine for me on 3 different hardware machines (all of them are running W10 x64, 21H1, build 19043.1151)
Only a minor cosmetic problem is observed as already reported with the  'check update' function. This function results do display confusing information to the user because the display does suggest to update the application which is already at the most up to date level !

**Comment by orangegrouptech** [comment]
Alright.
