### ISSUE TITLE
Not reporting correctly when more than one graphics card

### ISSUE THREAD

**Issue by IvanAclu** [orangegrouptech/Windows-11-Compatibility-Checker#14]
Using version 2.3.1 Windows-11-Compatibility-Checker reports
       GPU: DirectX 12.0, WDDM 1.3
This is not correct.  My PC has two graphic cards.
The first card is not Windows 11 compliant but the second card is.
The program result seems to have taken DirectX version from second card and WDDM version from first card.

DxDiag reports
For first graphics card
         DDI Version: 11.2
      Feature Levels: 11_0,10_1,10_0,9_3,9_2,9_1
        Driver Model: WDDM 1.3

For second graphics
         DDI Version: 12
      Feature Levels: 11_0,10_1,10_0,9_3,9_2,9_1
        Driver Model: WDDM 2.5

[DxDiag_x64.txt](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/6899490/DxDiag_x64.txt)

**Comment by orangegrouptech** [comment]
I'll look into it

**Comment by ThePhOeNiX810815** [comment]
@orangegrouptech hi, I reworked DXDiag data parsing by index, if there are more GFX cards present ... my thought is that for windows desktop rendering is important primary adapter, so I take it by index 0 ... take a look at it

@IvanAclu try this prerelease version, now it would analyze your first (primary) GFX card ... please check if it shows yhr right info

[Windows-11-Compatibility-Checker-2.3.3.zip](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/6911716/Windows-11-Compatibility-Checker-2.3.3.zip)

**Comment by IvanAclu** [comment]
Thanks for looking at this.
The prerelease file you linked to seems to be source code and not an executable so I cannot test it

**Comment by orangegrouptech** [comment]
@ThePhOeNiX810815 Using the executable that was in the bin\Debug\net45 folder, the GPU check failed for me with a single GPU
@IvanAclu I think the built executable is in src\bin\Debug\net45 folder

**Comment by ThePhOeNiX810815** [comment]
@orangegrouptech hi, can you please send me [phoenixvm@gmail.com] youx dxv.xml from the run when single GPU check fails ? ... it looks like various DXDiag versions returning results in different formatting ... thanks

**Comment by ThePhOeNiX810815** [comment]
@orangegrouptech thanks for report, I'm going to check it

**Comment by IvanAclu** [comment]
I ran the the following program;
Windows-11-Compatibility-Checker-2.3.3\src\bin\Debug\net45\Windows 11 Compatibility Checker WPF.exe
It gives an exception when checking the graphics.
   "Unhandled exception has been raised and reported."
The program completes when the exception is OK'd.
The dxv.xml file created is attached as a zip file.

[dxv.xml.zip](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/6912314/dxv.xml.zip)

**Comment by ThePhOeNiX810815** [comment]
@IvanAclu thanks for report, working on it ...

**Comment by ThePhOeNiX810815** [comment]
@IvanAclu hi, I've fixed some GFX and TPM checks issues, please, try this pre-release version ...thanks

Executable is in "src\bin\Debug\net45" folder.

[Windows-11-Compatibility-Checker-2.3.4.zip](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/6912624/Windows-11-Compatibility-Checker-2.3.4.zip)

**Comment by IvanAclu** [comment]
Pre-release 2.3.4 runs without an exception and reports;
GPU: DirectX 12.0. WDDM 2.5

Thanks for resolving this.

**Comment by ThePhOeNiX810815** [comment]
@IvanAclu thanks very much for test ... great ;-) ... now we just wait for @orangegrouptech to push official release
