### ISSUE TITLE
TPM Error

### ISSUE THREAD

**Issue by timea-techgirl** [orangegrouptech/Windows-11-Compatibility-Checker#15]
TPM is present and enabled but it shows incorrectly

![image](https://user-images.githubusercontent.com/7058205/127694513-23fe0bac-b69d-46bc-9ea8-99c7db052a79.png)

**Comment by orangegrouptech** [comment]
Could you send TPM.txt in %localappdata%\Orange Group\Windows 11 Compatibility Checker?

**Comment by timea-techgirl** [comment]
```


TpmPresent                : True
TpmReady                  : True
ManufacturerId            : 1229870147
ManufacturerIdTxt         : INTC
ManufacturerVersion       : 302.12 
ManufacturerVersionFull20 : 302.12.0.0                                                                                 
                                     
ManagedAuthLevel          : Full
OwnerAuth                 : 
OwnerClearDisabled        : False
AutoProvisioning          : Disabled
LockedOut                 : False
LockoutHealTime           : 2 hours
LockoutCount              : 0
LockoutMax                : 10
SelfTest                  : {}




```

**Comment by orangegrouptech** [comment]
weird how it doesn't contain a TpmEnabled line. Which version of Windows are you on?

**Comment by timea-techgirl** [comment]
Windows 10 LTSC 1809

**Comment by orangegrouptech** [comment]
Alright, I'll look into it when I create an 1809 VM

**Comment by ThePhOeNiX810815** [comment]
@orangegrouptech i think it's TPMReady flag which reflect TPM is enabled

**Comment by ThePhOeNiX810815** [comment]
@orangegrouptech naah, TpmReady is Server related flag

**Comment by ThePhOeNiX810815** [comment]
@timea-techgirl can you please try this on admin cmd ?

wmic /namespace:\\root\CIMV2\Security\MicrosoftTpm path Win32_Tpm get /value

My output is like:

IsActivated_InitialValue=TRUE
IsEnabled_InitialValue=TRUE
IsOwned_InitialValue=TRUE
ManufacturerId=1229346816
ManufacturerIdTxt=IFX
ManufacturerVersion=3.17
ManufacturerVersionFull20=Not Supported
ManufacturerVersionInfo=0311080
PhysicalPresenceVersionInfo=1.2
SpecVersion=1.2, 2, 2

Please check if you have IsEnabled flag here ... thNx

**Comment by timea-techgirl** [comment]
@ThePhOeNiX810815 There should be a double backslash `\\` after `namespace:`

I got this:
```
IsActivated_InitialValue=TRUE
IsEnabled_InitialValue=TRUE
IsOwned_InitialValue=TRUE
ManufacturerId=1229870147
ManufacturerIdTxt=INTC
ManufacturerVersion=302.12
ManufacturerVersionFull20=302.12.0.0
ManufacturerVersionInfo=496e74656c000000000000000000000000
PhysicalPresenceVersionInfo=1.2
SpecVersion=2.0, 0, 1.16
```

**Comment by orangegrouptech** [comment]
Well good then, it seems to have the stuff we need to check if it's enabled. I'll use this command instead of the original PowerShell Get-Tpm command then.

**Comment by ThePhOeNiX810815** [comment]
@timea-techgirl hi, I've fixed some GFX and TPM checks issues, please, try this pre-release version ...thanks
@orangegrouptech hi, I've distributed this version for all related issues ... according to feedback, please, take a look at it
- added ExceptionNotifier error handling, sending report on my e-mail by default, you can change it to yours
- reworked TPM check according to @timea-techgirl test
- reworked GFX and WDDM check ... now it's analyzing first (primary) display info, and recursively search for highest supported WDDM version

Executable is in "src\bin\Debug\net45" folder.

[Windows-11-Compatibility-Checker-2.3.4.zip](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/6912624/Windows-11-Compatibility-Checker-2.3.4.zip)

**Comment by orangegrouptech** [comment]
Alright thanks, I'll apply the updates
I won't apply ExceptionNotifier on this release, I'll add it in a future release where it can be controlled via a switch for privacy reasons - so that it doesn't send stuff without the person's consent
_cough_ telemetry _cough_

**Comment by orangegrouptech** [comment]
I just pushed out Patch 2.3.2 that includes these fixes. You guys can try it out and see if it works.

**Comment by timea-techgirl** [comment]
Hey! It works, all green now, no errors
