### ISSUE TITLE
running

### ISSUE THREAD

**Issue by tarbear123** [orangegrouptech/Windows-11-Compatibility-Checker#16]
what file type do i  need to look for/open to get the program running and is the type the same for all window files you download off of github?

**Comment by ThePhOeNiX810815** [comment]
@tarbear123 i'm not sure I understand ... archive / solution which you download from GitHub is clear source code solution ... if you want to run the application, you must compile the source by any IDE ... i prefer Visual Studio, but you can also use lightweight VS Code ... it's C# WPF project

**Comment by ThePhOeNiX810815** [comment]
@tarbear123 hi, does these informations help you ?

**Comment by Vichingo455** [comment]
If you want to run the checker, simply go to the latest release ( in this case Stable 2.4) and go under assets, then click the exe file of the one. Else, if you want to compile the checker you need to download the source code and Visual Studio + the C# and C++ components.
