### ISSUE TITLE
Wrong Secure Boot and CPU detection

### ISSUE THREAD

**Issue by hooddy** [orangegrouptech/Windows-11-Compatibility-Checker#17]
Me Intel NUC PC is fully compatible with Windows 11 (except CPU) and enabled GPT/Secure Boot on it. W11CC wrong say that Secure Boot is disabled.

![02](https://user-images.githubusercontent.com/6899176/128018495-b08230b6-c36e-477f-9f96-6e12ce9522dc.png)

And BTW is wrong detect for my CPU. It is Core i7

**Comment by orangegrouptech** [comment]
That's really weird. Could you take a screenshot of the CPU listed on CPU-Z and the Secure Boot status on msinfo32?

**Comment by hooddy** [comment]
Oh Im sorry it is correct detect my CPU. Its a mess on my table I confuse with my another PC. 
What about Secure Boot so msinfo32 says it is disabled and confirm-securebootuefi says false on it.
Sorry for the inaccuracy. I check UEFI right now and it's looks like that. 
![01](https://user-images.githubusercontent.com/6899176/128124586-06ec6935-d2cb-48bd-b785-0882b5102854.PNG)
![02](https://user-images.githubusercontent.com/6899176/128124600-b56f46c1-cf3f-4baf-980e-bc2daa0d0340.PNG)
ReadySunValley says Secure Boot is Ok so I wasn't warried about it.

**Comment by orangegrouptech** [comment]
The platform key isn't installed, try installing it in the BIOS

**Comment by hooddy** [comment]
Thank you. I check Install platform keys and boot with no results. Next I forced Secure Boot to defaults and it is seems to ok.
