### ISSUE TITLE
Secure Boot doesn't need to be enabled, just it needs to say supported if UEFI has Secure Boot option.

### ISSUE THREAD

**Issue by mads1153** [orangegrouptech/Windows-11-Compatibility-Checker#2]
Secure Boot doesn't need to be enabled, just it needs to say supported if UEFI has Secure Boot option.
It's because Windows 11 hardware requirements says "Secure Boot capable" that means it just needs the option, not enabling or disabling. WhyNotWin11 that did have more bad design does this already, so why not this app?
I remembered when I used PC Health Check app and I did have enabled TPM 2.0 in UEFI and no Secure Boot, it did say I can upgrade to Windows 11.

Link to Microsoft Windows 11 hardware requirements where it says system firmware: Secure Boot capable: https://docs.microsoft.com/en-us/windows/whats-new/windows-11-requirements

**Comment by mads1153** [comment]
More improvements that needs to be made:
No alerts at top of user interface despite for there is one red cross for Secure Boot (Secure Boot is not correct, but I thought on other things). 
Better mention of which storage to say this is harddrive where OS is installed on because I have two harddrives, one NVMe with OS installed and HDD for games and other things. 

I can open one more issue if you think it's better suited for this comment.

**Comment by orangegrouptech** [comment]
Hello,
the alerts doesn't list which specs are not compatible, right now it only warns the user if they're using the Enterprise SKU or if they're already using Windows 11.
I will see if there are any APIs that can check the drive type.
I am also working on making the PowerShell scripts act silently as for some reason it does not respect my process launch parameters.
![image](https://user-images.githubusercontent.com/63195743/123880667-b8d06c00-d975-11eb-8056-7eed81858b06.png)

**Comment by mads1153** [comment]
Ok, what about the issue in first post?

**Comment by orangegrouptech** [comment]
If the computer supports secure boot but is disabled, it's the same as a computer that doesn't support secure boot at all

**Comment by mads1153** [comment]
This answer wasn't like I expected, but OK. Secure Boot capable isn't the same as the computer needs Secure Boot to be enabled, just it needs to say it does support Secure Boot or not and if Secure Boot is enabled, then it should do like the app does already.

**Comment by krystian3w** [comment]
My PC revert enabled UEFI only + Secure Boot after reboot with 4 "long" beeps, so start in legacy firstly; so information may is not lie.

**Comment by mads1153** [comment]
PC Health app before it was temporarily removed due to feedbacks didn't ask for Secure Boot to be enabled and it did say it's possible to upgrade to Windows 11 after I have enabled AMD CPU fTPM Firmware that was required for TPM 2.0 only and didn't enable Secure Boot in UEFI. Other GitHub app like WhyNotWin11 does say it's supported, not supported or enabled. 
This app doesn't it to say supported and not supported, just disabled or enabled. That's why I created this issue.

**Comment by orangegrouptech** [comment]
> Other GitHub apps like WhyNotWin11 does say it's supported, not supported or enabled.
This app doesn't it to say supported and not supported, just disabled or enabled. That's why I created this issue.

Well, this app already does that. "Disabled" means that it is supported, just not enabled in the BIOS.
If it's not supported, there would not be a Registry key at all, and this app will also tell you if it's not supported.

![image](https://user-images.githubusercontent.com/63195743/126758517-3849ee0c-bce4-4648-891c-22b44b4efece.png)

**Comment by mads1153** [comment]
And then why red cross for Disabled and asking also for enabling Secure Boot in BIOS when that is not necessary to do since it's not required and it should be green or maybe yellow/orange. It's fine if it say "Optional: Enable Secure Boot in BIOS" instead including the other colour for checkmark. It should be red cross for only unsupported that who doesn't have Secure Boot at all. This is only thing left that looks wrong. I just trying to say what I mean that could be more correct and I see you are doing good job with the app development.

**Comment by orangegrouptech** [comment]
Took a look at another one of Microsoft's documents, and it's stated that Secure Boot is required.

![image](https://user-images.githubusercontent.com/63195743/127249784-2e1d4bc8-a34c-4c57-8c98-96e9a1129a8c.png)

**Comment by Vichingo455** [comment]
> Took a look at another one of Microsoft's documents, and it's stated that Secure Boot is required.
> 
> ![image](https://user-images.githubusercontent.com/63195743/127249784-2e1d4bc8-a34c-4c57-8c98-96e9a1129a8c.png)

No, Siam Alam has published a video a few weeks ago focused on bypassing TPM and Secure Boot requirements. But, if you use the ISO of Windows 10 and replace its install.wim image with the one of Windows 11, you are able to install Windows 11 without UEFI, Secure Boot and TPM

**Comment by orangegrouptech** [comment]
The whole purpose of this checker is to check if your computer "legally" supports Windows 11. You could literally bypass all restrictions except the EFI one by using DISM to install.

**Comment by Vichingo455** [comment]
> The whole purpose of this checker is to check if your computer "legally" supports Windows 11. You could literally bypass all restrictions except the EFI one by using DISM to install.

EFI too

**Comment by orangegrouptech** [comment]
Point stands

**Comment by mads1153** [comment]
It does say "Must include/implement component beside REQUIRED" that doesn't mean it's required to have it enabled, just the option is there.

**Comment by mads1153** [comment]
Ok, we will see if the next PC health app will not check this Secure Boot or not later because original one didn't do it to say it's required to be enabled.

**Comment by orangegrouptech** [comment]
I don't think that would ever come back lol

**Comment by krystian3w** [comment]
I suppose MS use WU mechanism to check instead repair app.

**Comment by mads1153** [comment]
With the new PC Health Check app not many days ago, it does only checks if Secure Boot is supported or not and it will list all that checks with Windows 11 requirements is passed or not, nothing that makes it to say you need to enable Secure Boot. 

So I was right.

**Comment by krystian3w** [comment]
But this can block see updates and need weekly run fun WSUS: https://gitlab.com/wsusoffline/wsusoffline
