### ISSUE TITLE
did not detect tpm

### ISSUE THREAD

**Issue by Comic-Tom** [orangegrouptech/Windows-11-Compatibility-Checker#20]
hello
![asdasdasdd](https://user-images.githubusercontent.com/89974115/131823295-21caa5f1-5bb4-4c22-a10f-32d9a5fa5323.png)

**Comment by Comic-Tom** [comment]
[TPMresult.txt](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/7097985/TPMresult.txt)
also adding this

**Comment by orangegrouptech** [comment]
It looks like your TPM was not enabled

**Comment by ThePhOeNiX810815** [comment]
Hi @orangegrouptech 

I've do some changes on TPM check conditions. take a look at it.

thNx

[TPM Check.txt](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/7109635/TPM.Check.txt)

**Comment by Vichingo455** [comment]
> hello ![asdasdasdd](https://user-images.githubusercontent.com/89974115/131823295-21caa5f1-5bb4-4c22-a10f-32d9a5fa5323.png)

Seems like you have TPM 1.2. Note that Windows 11 requires TPM 2.0

**Comment by orangegrouptech** [comment]
I'm gonna need more than just a Device Manager screenshot, please send over the TPMresult.txt file located in %localappdata%\Orange Group\Windows 11 Compatibility Checker
