### ISSUE TITLE
Detected BIOS Legacy

### ISSUE THREAD

**Issue by Vichingo455** [orangegrouptech/Windows-11-Compatibility-Checker#3]
My BIOS Mode is UEFI, but the compatibility checker has detected a BIOS Legacy. Screenshot is here
![image](https://user-images.githubusercontent.com/59311016/123908025-216c1880-d977-11eb-8421-71096734bd31.png)
I have started the Windows 11 Installer and I can run Windows 11
![image](https://user-images.githubusercontent.com/59311016/123908616-0d74e680-d978-11eb-92ab-ba8318f9f5c0.png)

**Comment by orangegrouptech** [comment]
Hello,
thanks for reporting this issue. Are you using the latest version (Stable 1.4) of the tool?
Thanks.

**Comment by Vichingo455** [comment]
Yes

**Comment by orangegrouptech** [comment]
Alright. Could you send me BIOSMode.txt in %localappdata%\Orange Group\Windows 11 Compatibility Checker?
Thanks.

**Comment by orangegrouptech** [comment]
actually screw what I said above, try and see if Patch 1.4.1 works

**Comment by Vichingo455** [comment]
[BIOSMode.txt](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/6738640/BIOSMode.txt)

**Comment by Vichingo455** [comment]
Patch 1.4.1 give me the same results. For the information, I have an ASUS computer

**Comment by orangegrouptech** [comment]
Try Patch 1.4.2.

**Comment by Vichingo455** [comment]
Thank you. Now it detected BIOS UEFI
![image](https://user-images.githubusercontent.com/59311016/123929030-baf2f480-d98e-11eb-833c-4e638fc1b070.png)
