### ISSUE TITLE
Improving the user interface

### ISSUE THREAD

**Issue by Oleg-Chashko** [orangegrouptech/Windows-11-Compatibility-Checker#4]
1. Please correct the circumcision of the word.
<img width="757" alt="Screen Shot 2021-07-09 at 11 41 44" src="https://user-images.githubusercontent.com/62497891/125061249-6bf34080-e0ad-11eb-8988-2b685d178ac8.png">

**Comment by orangegrouptech** [comment]
Thanks for bringing this up, working on a patch now

**Comment by orangegrouptech** [comment]
Hello, could you check if Patch 2.0.3 fixes this issue?
Thanks.

**Comment by Oleg-Chashko** [comment]
Hello, @orangegrouptech 

Point number 1 is corrected.
<img width="755" alt="Screen Shot 2021-07-09 at 12 50 20" src="https://user-images.githubusercontent.com/62497891/125067566-ba580d80-e0b4-11eb-9bc4-f1e4e739786f.png">

But I would like the alignment to be in the middle. It would be a little prettier that way.

<img width="755" alt="Screen Shot 2021-07-09 at 12 50 20" src="https://user-images.githubusercontent.com/62497891/125068307-9fd26400-e0b5-11eb-993e-7a247e95b554.png">

Thanks.

**Comment by orangegrouptech** [comment]
i'll work on that.

**Comment by orangegrouptech** [comment]
I fixed this in version 2.1. Try it out and you can give some feedback if you want

**Comment by Oleg-Chashko** [comment]
<img width="525" alt="Screen Shot 2021-07-14 at 09 08 44" src="https://user-images.githubusercontent.com/62497891/125578990-6f7fdb67-4e8f-4a5b-a923-9c7106633b14.png">

**Comment by Oleg-Chashko** [comment]
I think when you fix it, you can close it. Thank you.

**Comment by orangegrouptech** [comment]
Shucks. Well then, I'll probably fix this and release this together with another update that would bring some other new stuff I'm planning to add too.

**Comment by Oleg-Chashko** [comment]
I will be waiting for your updates, good luck. :)

**Comment by orangegrouptech** [comment]
Fixed on version 2.2. You can check it out and see if it looks fine now.

**Comment by Oleg-Chashko** [comment]
I think, you can close it. Thank you. 👍🏻
