### ISSUE TITLE
Add a check for Internet connection?

### ISSUE THREAD

**Issue by Oleg-Chashko** [orangegrouptech/Windows-11-Compatibility-Checker#5]
Maybe sometime in the future, add a check for Internet connection?
These are requirements for Windows 11 Home.
<img width="763" alt="125064282-c6da6700-e0b0-11eb-99ec-c8361accfae2" src="https://user-images.githubusercontent.com/62497891/125068870-43bc0f80-e0b6-11eb-8748-9ee9a3d9752a.png">

**Comment by orangegrouptech** [comment]
Well, if you don't have an Internet connection you can't really download this app though.

**Comment by Oleg-Chashko** [comment]
> Well, if you don't have an Internet connection you can't really download this app though.

- That's an option you didn't consider?
What makes you think I downloaded it from the Internet. An acquaintance gave it to me on a usb flash drive.

- Are you sure that all the computers where Windows 11 will be installed will be connected to the Internet?
I'm not so sure about that.

- Yes, and then you also got windows 11 bootable usb.
As surprising as this may sound. But, I all my software on my server. And I exchange a lot, via USB flash.

- I understand your point, but there is such low probability of that.
It depends on what country you live in and whether it is a city or a village. Some residents are only connected to ADSL, and some have only 3G. If you and I do not have problems with the Internet, it does not mean that others do not have them too.

I will say this, I am in Germany and here in some villages there is no wired Internet and no mobile normal, people have to go up the mountain to make a call. Deutsche Telekom does not want to install cable because it is not profitable. There is a private satellite Internet for the whole village. With a gigabyte fee for Internet traffic. 

P.S.: But it's up to you, it's still your project, not mine. ;)

**Comment by Oleg-Chashko** [comment]
One of the possibilities.
Option how to implement this: Your program checks your current Windows license and if you have Windows Home edition installed. A simple warning stating that Internet is required should suffice.

**Comment by orangegrouptech** [comment]
> > Well, if you don't have an Internet connection you can't really download this app though.
> 
> * That's an option you didn't consider?
>   What makes you think I downloaded it from the Internet. An acquaintance gave it to me on a usb flash drive.
> * Are you sure that all the computers where Windows 11 will be installed will be connected to the Internet?
>   I'm not so sure about that.
> * Yes, and then you also got windows 11 bootable usb.
>   As surprising as this may sound. But, I all my software on my server. And I exchange a lot, via USB flash.
> * I understand your point, but there is such low probability of that.
>   It depends on what country you live in and whether it is a city or a village. Some residents are only connected to ADSL, and some have only 3G. If you and I do not have problems with the Internet, it does not mean that others do not have them too.
> 
> I will say this, I am in Germany and here in some villages there is no wired Internet and no mobile normal, people have to go up the mountain to make a call. Deutsche Telekom does not want to install cable because it is not profitable. There is a private satellite Internet for the whole village. With a gigabyte fee for Internet traffic.
> 
> P.S.: But it's up to you, it's still your project, not mine. ;)

Fair enough, I'll consider that

**Comment by orangegrouptech** [comment]
> One of the possibilities.
> Option how to implement this: Your program checks your current Windows license and if you have Windows Home edition installed. A simple warning stating that Internet is required should suffice.

Yeah, that's a good idea since those using Pro or Enterprise SKUs don't really need to worry about this

**Comment by Vichingo455** [comment]
In my opinion is better adding a "Internet connection speed" check.

**Comment by orangegrouptech** [comment]
> In my opinion is better adding an "Internet connection speed" check.

Well, you only need Internet, even if it's 10MB/s, it's still Internet

**Comment by orangegrouptech** [comment]
I added this in version 2.1. Try it out and you can give some feedback if you want

**Comment by Oleg-Chashko** [comment]
> I added this in version 2.1. Try it out and you can give some feedback if you want

Unfortunately, I can't, since Windows Enterprise is installed. I think you can close. Thank you.
