### ISSUE TITLE
Please do not see the "Powershell" windows when running the program

### ISSUE THREAD

**Issue by Oleg-Chashko** [orangegrouptech/Windows-11-Compatibility-Checker#6]
Please do not see the "Powershell" windows when running the program.

**Comment by orangegrouptech** [comment]
Right now the solution I try to apply to it doesn't really work, I'll see if I can find another method to fix this issue.

![image](https://user-images.githubusercontent.com/63195743/125077141-59035f00-e0f3-11eb-8390-95f5c3e0f34b.png)

**Comment by orangegrouptech** [comment]
I fixed this in version 2.1. Try it out and you can give some feedback if you want

**Comment by Oleg-Chashko** [comment]
There are no more "Powershell" windows, you can close it. Thank you.
