### ISSUE TITLE
[Raise Condition] Null Reference Exception

### ISSUE THREAD

**Issue by ThePhOeNiX810815** [orangegrouptech/Windows-11-Compatibility-Checker#8]
I assume there's some weird raise condition for this ... unable to reproduce

### Screenshot:
![screen](https://user-images.githubusercontent.com/23176319/126039264-5fb3c34f-882d-41ab-b906-01a8a18ae94b.jpg)

### StackTrace:
[stackTrace.txt](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/6834798/stackTrace.txt)

**Comment by orangegrouptech** [comment]
Judging by the look of the buttons and the fact that the "Windows 11 Compatibility at a glance" phrase isn't bold, it looks like you might be using the WindowsForms version of the app (version 1.x), which is seriously old. Try and see if this happens with the latest stable version of this app.

**Comment by orangegrouptech** [comment]
To check the version of the app you have, click the About button at the bottom left. The latest stable version is 2.2.1.

![image](https://user-images.githubusercontent.com/63195743/126054339-ac8fc136-6b80-4969-b298-0f35c5569f8a.png)

**Comment by ThePhOeNiX810815** [comment]
Hi there

 

Yes, I was using version 1.4.2. Already downloaded latest.

 

thNx for info,

 

Regards,

 

Peter Machaj 



Mallého 1085/12

909 01 Skalica
Slovenská republika

 

Tel: +421/(0)951 262 032

Skype: uncanny104

Facebook: Peter Machaj
E-mail:  ***@***.***> ***@***.***

 

 <https://www.linkedin.com/in/peter-machaj>

**Comment by orangegrouptech** [comment]
that's weird.

**Comment by Vichingo455** [comment]
Try installing the latest version of .NET Framework. If you have already installed it, try enabling all subfeatures of it
