### ISSUE TITLE
TPM Version check

### ISSUE THREAD

**Issue by ThePhOeNiX810815** [orangegrouptech/Windows-11-Compatibility-Checker#9]
How about this ?

[TPM.txt](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/6835836/TPM.txt)

**Comment by orangegrouptech** [comment]
thanks, i'll take a look at it.

**Comment by orangegrouptech** [comment]
Added in 2.3, you can check it out

**Comment by YuriPet** [comment]
The version of TPM on my PC determined incorrectly.
![TPM](https://user-images.githubusercontent.com/11704993/126680565-ea2bc4f0-e019-4c68-bf24-4cec80bb06c5.png)

**Comment by mads1153** [comment]
I did have this problem too.

**Comment by orangegrouptech** [comment]
Looking into it

**Comment by ThePhOeNiX810815** [comment]
@orangegrouptech ... I've changed WMI query, please, can you check it out ? ... I can't because my 8300 SFF have TPM 1.2.

[TPM Version.txt](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/6866787/TPM.Version.txt)

**Comment by orangegrouptech** [comment]
alright, i'll roll out a patch later

**Comment by orangegrouptech** [comment]
Try this out
This is a prerelease build, so if you click check for updates it'll give you a warning. Just ignore it since you guys are authorised to test this build

[Windows 11 Compatibility Checker WPF.zip](https://github.com/orangegrouptech/Windows-11-Compatibility-Checker/files/6867056/Windows.11.Compatibility.Checker.WPF.zip)

**Comment by YuriPet** [comment]
All OK!
![TPM_2](https://user-images.githubusercontent.com/11704993/126749025-fbf325dc-c8d1-43a1-a2a6-663d513d2abf.png)

**Comment by ThePhOeNiX810815** [comment]
All OK!
![image](https://user-images.githubusercontent.com/23176319/126755879-a7c13569-61a4-46d5-a2b1-a8f9662857b8.png)

**Comment by orangegrouptech** [comment]
Alright, I'll officially roll this build out and close this issue after that

**Comment by orangegrouptech** [comment]
Just pushed out 2.3.1 to stable

**Comment by mads1153** [comment]
Can also confirm this is working fine for me.
